# Generated by Django 5.0 on 2024-07-16 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('GRN_no', models.TextField(primary_key=True, serialize=False)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('recieved_from', models.TextField(blank=True, null=True)),
                ('transporter_name', models.TextField(blank=True, null=True)),
                ('truck_no', models.TextField(blank=True, null=True)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('store_keeper', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_orders',
            fields=[
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('PR_no', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('site_name', models.TextField()),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('requested_by', models.TextField(blank=True, null=True)),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('PR_total_price', models.FloatField(blank=True, null=True)),
                ('PR_before_vat', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='Pending', null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('measurement_type', models.TextField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PR_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_vat', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('remaining', models.FloatField()),
                ('item_measurement', models.TextField(blank=True, null=True)),
                ('PR_no', models.ForeignKey(blank=True, db_column='PR_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='GRN.purchase_orders')),
            ],
        ),
        migrations.CreateModel(
            name='GRN_item',
            fields=[
                ('grn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('GRN_no', models.ForeignKey(db_column='GRN_no', on_delete=django.db.models.deletion.CASCADE, to='GRN.grn')),
                ('PR_no', models.ForeignKey(db_column='PR_no', on_delete=django.db.models.deletion.CASCADE, to='GRN.purchase_orders')),
            ],
        ),
        migrations.AddField(
            model_name='grn',
            name='PR_no',
            field=models.ForeignKey(blank=True, db_column='PR_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='GRN.purchase_orders'),
        ),
    ]
