# Generated by Django 5.0 on 2024-07-17 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HS_code',
            fields=[
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField()),
            ],
        ),
    ]
