# Generated by Django 5.0 on 2024-07-21 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GRN", "0002_hs_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grn",
            name="PR_no",
        ),
        migrations.RemoveField(
            model_name="grn_item",
            name="PR_no",
        ),
    ]
