# Generated by Django 5.0.7 on 2024-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRN', '0003_remove_grn_pr_no_remove_grn_item_pr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn_item',
            name='measurement_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn_item',
            name='measurement_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn_item',
            name='no_of_bags',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn_item',
            name='per_unit_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn_item',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
