# Generated by Django 5.0.7 on 2024-08-12 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRN', '0006_rename_no_of_bags_grn_item_no_of_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_GRN_items',
            fields=[
                ('item_name', models.TextField(blank=True)),
                ('total_no_of_unit', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True)),
                ('inventory_GRN_items_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
