# Generated by Django 5.0.7 on 2024-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GRN", "0014_alter_purchase_orders_pr_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase_orders",
            name="PR_before_vat",
            field=models.FloatField(blank=True, db_column="pr_before_vat", null=True),
        ),
        migrations.AlterField(
            model_name="purchase_orders",
            name="PR_total_price",
            field=models.FloatField(blank=True, db_column="pr_total_price", null=True),
        ),
    ]
