# Generated by Django 5.0.7 on 2024-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GRN", "0015_alter_purchase_orders_pr_before_vat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase_orders",
            name="excise_tax",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
