# Generated by Django 5.0.7 on 2025-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRN', '0017_alter_pr_item_pr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tin_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
