# Generated by Django 5.0

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GRN", "0019_actualpurchase_actualpurchaseitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_number", models.CharField(max_length=255, unique=True)),
                ("installment_number", models.PositiveIntegerField(default=1)),
                ("payment_date", models.DateField()),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("partial", "Partial"), ("full", "Full")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("remark", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status_remark", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendor_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_vendor_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_vendor_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pr",
                    models.ForeignKey(
                        db_column="pr_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_payments",
                        to="GRN.purchase_orders",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-installment_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="vendorpayment",
            constraint=models.UniqueConstraint(
                fields=("pr", "installment_number"),
                name="uniq_vendor_payment_installment_per_pr",
            ),
        ),
    ]
