# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GRN", "0021_vendorpayment_actual_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase_orders",
            name="fully_paid_missing_actual_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
