# Generated by Django 5.0 on 2024-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgrn',
            name='recieved_by',
        ),
        migrations.AddField(
            model_name='fgrn_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fgrn_item',
            name='measurement_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fgrn_item',
            name='no_of_bags',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
