# Generated by Django 5.0 on 2024-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FGRN", "0002_remove_fgrn_recieved_by_fgrn_item_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgrn",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fgrn",
            name="recieved_by",
            field=models.TextField(blank=True, null=True),
        ),
    ]
