# Generated by Django 5.0 on 2024-07-16 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('item_name', models.TextField(blank=True)),
                ('quantity', models.FloatField(blank=True)),
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('MR_no', models.TextField(primary_key=True, serialize=False)),
                ('MR_date', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('MR_store', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MR_item',
            fields=[
                ('quantity', models.FloatField(blank=True)),
                ('item_name', models.TextField()),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_type', models.TextField(blank=True, null=True)),
                ('MR_no', models.ForeignKey(db_column='MR_no', on_delete=django.db.models.deletion.CASCADE, to='MR.mr')),
            ],
        ),
    ]
