# Generated by Django 5.0.7 on 2024-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0002_inventory_no_of_unit_inventory_unit_measurment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
