# Generated by Django 5.0.7 on 2024-07-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0003_inventory_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mr_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr_item',
            name='measurement_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr_item',
            name='no_of_bags',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr_item',
            name='per_unit_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr_item',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
