# Generated by Django 5.0.7 on 2024-08-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0005_rename_unit_measurment_inventory_measurement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mr_item',
            old_name='no_of_bags',
            new_name='no_of_unit',
        ),
        migrations.RenameField(
            model_name='mr_item',
            old_name='description',
            new_name='unit_type',
        ),
        migrations.RemoveField(
            model_name='mr_item',
            name='measurement_unit',
        ),
    ]
