# Generated by Django 5.0.7 on 2024-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0006_rename_no_of_bags_mr_item_no_of_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.TextField(blank=True),
        ),
    ]
