# Generated by Django 5.0.7 on 2024-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0008_remove_inventory_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
