# Generated by Django 5.0.7 on 2024-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0011_inventory_mr_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_mr_items',
            name='measurement_type',
        ),
        migrations.RemoveField(
            model_name='inventory_mr_items',
            name='unit_type',
        ),
    ]
