# Generated by Django 5.0.7 on 2024-08-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0014_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mr',
            old_name='MR_date',
            new_name='date',
        ),
    ]
