# Generated by Django 5.0 on 2024-07-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FGRN", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgrn",
            name="total_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
