# Generated by Django 5.0.7 on 2024-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0003_fgrn_description_fgrn_recieved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='items_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
            ],
        ),
    ]
