# Generated by Django 5.0.7 on 2024-08-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0004_finished_goods_measurement_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fgrn_item',
            old_name='no_of_bags',
            new_name='no_of_unit',
        ),
    ]
