# Generated by Django 5.0.7 on 2024-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0005_rename_no_of_bags_fgrn_item_no_of_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods',
            name='no_of_unit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
