# Generated by Django 5.0.7 on 2024-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0006_alter_finished_goods_no_of_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgrn_item',
            name='unit_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
