# Generated by Django 5.0.7 on 2024-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0009_fgrnopening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgrn_item',
            name='item_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
