# Generated by Django 5.0.7 on 2024-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0010_alter_fgrn_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgrn_item',
            name='item_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
