# Generated by Django 5.0.7 on 2024-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0014_inventory_fgrn_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fgrn',
            options={'ordering': ['FGRN_no']},
        ),
        migrations.AlterModelOptions(
            name='fgrn_item',
            options={'ordering': ['FGRN_no']},
        ),
    ]
