# Generated by Django 5.0.7 on 2024-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0015_alter_fgrn_options_alter_fgrn_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgrn',
            name='branch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
