# Generated by Django 5.0.7 on 2024-11-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0026_inventory_order_items'),
        ('FGRN', '0016_fgrn_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='FGRN.finished_goods')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DN.inventory_order_items')),
            ],
        ),
    ]
