# Generated by Django 5.0.7 on 2024-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGRN', '0017_finishedgoodsgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsgroup',
            name='group_name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
