# Generated by Django 5.0.7 on 2024-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0027_remove_inventory_order_items_balance_id_and_more'),
        ('FGRN', '0018_alter_finishedgoodsgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedgoodsgroup',
            name='order_items',
        ),
        migrations.AddField(
            model_name='finishedgoodsgroup',
            name='order_items',
            field=models.ManyToManyField(to='DN.inventory_order_items'),
        ),
    ]
