# Generated by Django 5.0 on 2024-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="orders",
            fields=[
                ("customer_name", models.TextField()),
                ("tin_no", models.TextField()),
                ("serial_no", models.TextField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                ("invoice", models.TextField(blank=True, null=True, unique=True)),
                ("invoice_type", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("measurement", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("order_quantity", models.IntegerField(blank=True, null=True)),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("remaining", models.IntegerField(blank=True, null=True)),
                ("before_vat", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("withholding_amount", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="delivery",
            fields=[
                (
                    "delivery_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("delivery_date", models.DateField(blank=True)),
                ("delivery_quantity", models.IntegerField(blank=True)),
                ("truck_number", models.TextField(blank=True, null=True)),
                ("driver_name", models.TextField(blank=True, null=True)),
                ("recipient_name", models.TextField(blank=True, null=True)),
                ("delivery_comment", models.TextField(blank=True, null=True)),
                (
                    "serial_no",
                    models.ForeignKey(
                        db_column="serial_no",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="DN.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="trial_delivery",
            fields=[
                ("name", models.IntegerField(primary_key=True, serialize=False)),
                ("delivery_date", models.DateField(blank=True)),
                ("delivery_quantity", models.IntegerField(blank=True)),
                ("truck_number", models.TextField(blank=True, null=True)),
                ("driver_name", models.TextField(blank=True, null=True)),
                ("recipient_name", models.TextField(blank=True, null=True)),
                ("delivery_comment", models.TextField(blank=True, null=True)),
                (
                    "serial_no",
                    models.ForeignKey(
                        db_column="serial_no",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="DN.orders",
                    ),
                ),
            ],
        ),
    ]
