# Generated by Django 5.0 on 2024-07-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trial_delivery',
            options={'managed': False},
        ),
    ]
