# Generated by Django 5.0 on 2024-07-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0002_alter_delivery_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='trial_delivery',
            table='trial_delivery',
        ),
    ]
