# Generated by Django 5.0 on 2024-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0003_alter_delivery_table_alter_orders_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trial_delivery',
            options={},
        ),
    ]
