# Generated by Django 5.0.7 on 2024-08-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('no_of_unit', models.FloatField(blank=True, null=True)),
                ('unit_type', models.FloatField(blank=True, null=True)),
                ('price_per_kg', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('order_quantity', models.FloatField(blank=True, null=True)),
                ('remaining_quantity', models.FloatField(blank=True, null=True)),
                ('remaining_unit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='remaining',
        ),
    ]
