# Generated by Django 5.0 on 2024-08-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0002_orders_items_remove_orders_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders_items",
            old_name="price",
            new_name="per_unit_kg",
        ),
        migrations.RenameField(
            model_name="orders_items",
            old_name="price_per_kg",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="orders",
            name="total_bags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders_items",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
