# Generated by Django 5.0 on 2024-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0003_rename_price_orders_items_per_unit_kg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders_items",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
