# Generated by Django 5.0 on 2024-08-04 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0004_orders_items_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders_items",
            old_name="price",
            new_name="total_price",
        ),
    ]
