# Generated by Django 5.0 on 2024-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0005_rename_price_orders_items_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="total_price",
            new_name="final_price",
        ),
        migrations.AddField(
            model_name="orders",
            name="reciveable",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="vat_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
