# Generated by Django 5.0.7 on 2024-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0006_rename_total_price_orders_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_items',
            name='unit_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
