# Generated by Django 5.0.7 on 2024-08-05 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0007_alter_orders_items_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_items',
            name='serial_no',
            field=models.ForeignKey(db_column='serial_no', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='DN.orders'),
            preserve_default=False,
        ),
    ]
