# Generated by Django 5.0.7 on 2024-08-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0008_orders_items_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_items',
            name='order_quantity',
        ),
    ]
