# Generated by Django 5.0 on 2024-08-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0009_remove_orders_items_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="delivery_quantity",
        ),
        migrations.CreateModel(
            name="delivery_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("no_of_unit", models.FloatField(blank=True, null=True)),
                ("unit_type", models.TextField(blank=True, null=True)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("per_unit_kg", models.FloatField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "delivery_number",
                    models.ForeignKey(
                        db_column="delivery_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DN.delivery",
                    ),
                ),
            ],
        ),
    ]
