# Generated by Django 5.0 on 2024-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0010_remove_delivery_delivery_quantity_delivery_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="total_bags",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="total_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
