# Generated by Django 5.0 on 2024-08-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0011_delivery_total_bags_delivery_total_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery_items",
            name="serial_no",
            field=models.ForeignKey(
                db_column="serial_no",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="DN.delivery",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery_items",
            name="delivery_number",
            field=models.ForeignKey(
                db_column="delivery_number",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="DN.delivery",
            ),
        ),
    ]
