# Generated by Django 5.0.7 on 2024-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0015_rename_name_customer_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='addis', max_length=100),
            preserve_default=False,
        ),
    ]
