# Generated by Django 5.0.7 on 2024-09-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0016_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="serial_no",
            field=models.ForeignKey(
                db_column="serial_no",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="deliveries",
                to="DN.orders",
            ),
        ),
    ]
