# Generated by Django 5.0.7 on 2024-09-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0017_alter_delivery_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders_items",
            name="serial_no",
            field=models.ForeignKey(
                db_column="serial_no",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="DN.orders",
            ),
        ),
    ]
