# Generated by Django 5.0.7 on 2024-09-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0018_alter_orders_items_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="serial_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
