# Generated by Django 5.0.7 on 2024-09-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0020_alter_delivery_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="serial_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="DN.orders",
            ),
        ),
    ]
