# Generated by Django 5.0.7 on 2024-10-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0021_alter_delivery_serial_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="tin_no",
            field=models.TextField(blank=True, null=True),
        ),
    ]
