# Generated by Django 5.0.7 on 2024-10-01 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DN", "0022_alter_orders_tin_no"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
    ]
