# Generated by Django 5.0.7 on 2024-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0024_inventory_dn_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['delivery_number']},
        ),
        migrations.AlterModelOptions(
            name='delivery_items',
            options={'ordering': ['delivery_number']},
        ),
    ]
