# Generated by Django 5.0.7 on 2024-12-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0026_inventory_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company']},
        ),
    ]
