# Generated by Django 5.0.7 on 2024-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0026_inventory_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_order_items',
            name='balance_id',
        ),
        migrations.AlterField(
            model_name='inventory_order_items',
            name='item_name',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
