# Generated by Django 5.0.7 on 2025-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0027_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
