# Generated by Django 5.0.7 on 2025-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0028_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_order_items',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
