# Generated by Django 5.0.7 on 2026-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DN', '0031_orders_void_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_items',
            name='measurement_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
